# name: ccsafe ci-cd

# on:
#   push:
#     branches:
#       - dev
#       - main

# jobs:
#   run-tests:
#     if: github.ref == 'refs/heads/dev'
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Set Up Python
#         uses: actions/setup-python@v3
#         with:
#           python-version: "3.11"

#       - name: Install Dependencies
#         run: |
#           pip install -r requirements.txt

#       - name: Run Pytest for `transaction_test.py`
#         run: pytest tests/transaction_test.py

#   deploy-to-prod:
#     if: github.ref == 'refs/heads/main'
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Authenticate to GCP
#         uses: google-github-actions/auth@v1
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       - name: Setup Google Cloud SDK
#         uses: google-github-actions/setup-gcloud@v1
#         with:
#           project_id: ${{ secrets.GCP_PROJECT_ID }}

#       - name: Upload Spark Job to GCS
#         run: |
#           gsutil cp ${{ env.SPARK_JOB_FILE }} gs://${{ env.GCS_BUCKET }}/sparkjob/

#       - name: Upload Airflow DAG to Composer
#         run: |
#           gcloud composer environments storage dags import \
#             --environment ${{ env.COMPOSER_ENV }} \
#             --location ${{ env.REGION }} \
#             --source ${{ env.DAG_FILE }}
